# Generated by Django 4.2 on 2023-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.URLField()),
                ('shortcode', models.CharField(max_length=10, unique=True)),
                ('visited', models.BigIntegerField(default=0)),
            ],
        ),
    ]
