# Generated by Django 4.2 on 2023-04-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='shortcode',
        ),
    ]
