# Generated by Django 4.2 on 2023-04-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_url_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortcode',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
