# Generated by Django 4.2 on 2023-05-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_url_longurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shorturl',
            field=models.URLField(default='none', max_length=1000, unique=True),
        ),
    ]
