# Generated by Django 4.2 on 2023-05-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_url_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.URLField(default='localhost:8000', unique=True),
        ),
    ]
