# Generated by Django 4.2 on 2023-05-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_url_shortcode_alter_url_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.CharField(),
        ),
    ]
