# Generated by Django 4.2 on 2023-05-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_url_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='url',
            constraint=models.CheckConstraint(check=models.Q(('shorturl__isnull', False), ('shorturl__gt', '')), name='non_empty_shorturl'),
        ),
    ]
