# Generated by Django 4.2 on 2023-05-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_url_shorturl_url_non_empty_shorturl'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='url',
            name='non_empty_shorturl',
        ),
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.URLField(default='default_value', unique=True),
        ),
    ]
