# Generated by Django 4.2 on 2023-05-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_url_non_empty_shorturl_alter_url_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.URLField(default='http://google.com/', max_length=110),
        ),
    ]
