# Generated by Django 4.2 on 2023-05-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_url_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.URLField(max_length=110, null=True),
        ),
    ]
